/**:
  ros__parameters:
    action_name: "robotino_behavior_server"
    tick_frequency: 50
    groot2_port: 1667
    ros_plugins_timeout: 10000

    plugins:
      - behaviortree_cpp/bt_plugins
      - robotino_behavior_tree/bt_plugins

    behavior_trees:
      - robotino_behavior_tree/behavior_trees
